# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplistapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplistclass',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
