# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-29 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplistapp', '0002_auto_20170915_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoplistclass',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='shoplistclass',
            name='entered_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
